# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/codehub/VIVADO/Nexys-4-DDR-Music-Looper/src/constraints/Nexys4DDR_Master.xdc

# IP: D:/codehub/VIVADO/DDR_/src/ip/mig_7series_0/mig_7series_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet

# IP: D:/codehub/VIVADO/DDR_/src/ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
